### ISSUE TITLE
How to generate periodic MOF  force field?

### ISSUE THREAD

**Issue by realJohnLock** [molmod/QuickFF#9]
Hi QuickFF developers,
I am going to implement QuickFF force field in CP2K package to simulate MOF reactions. I had installed QuickFF in my local computer and I had read your user guide and repeated the tutorials (include biphenyl). I had set QuickFF output CHARMM style outputs, both psf and prm. But I still have something confuse me. The tutorials only deal with single molecules QuickFF, there is nothing indicate how to execute a complete periodic MOF/COF procedure. If I want to generate periodic MOF/COF QuickFF, should I opt the MOF/COF with periodic condition in gaussian? Could you give me an example or tips? 
Any suggestions will be appreciated.

**Comment by lvduyfhu** [comment]
Hi,

thank you for your comment and sharing your experience. Indeed, there is not yet a tutorial on how to generate force fields for periodic structures. In the near future, we will indeed expand on the list of tutorials, including constructing force fields for metal-organic frameworks. 

For the moment, the qff.py script (http://molmod.github.io/QuickFF/ug.html#quickff-main-script-qff-py) does not support the use of Gaussian FCHK input for periodic input data (it is supported for cluster input), only VASP XML files are supported for periodic data. Using VASP XML files as input in qff.py is similar as using Gaussian FCHK files.

However, as described in the documentation (http://molmod.github.io/QuickFF/ug.html#importing-quickff-as-a-library), one can also use QuickFF as a library, which allows more flexibility for the input by extracting the Hessian from any file as a numpy array through a custom piece of Python code. As a small added tip here, even though the documentation describes how to define custom programs (i.e. custom sequence of fitting steps) while using QuickFF as a library, nothing stops you from just using the QuickFF-as-a-library feature to only adapt the extraction of the Hessian from a custom input file and applying the default program (BaseProgram).

I hope this was useful. Don't hesitate to contact us again if you would desire additional assistance.
Louis Vanduyfhuys

**Comment by realJohnLock** [comment]
Hi,
Thank you for your reply. I am not familiar with VASP, so I am incline to try the cluster model first. I will do some real MOF jobs with cluster model in the next few weeks. Some QuickFF force field terms are not supported by CP2K right now, I think I need to add the missing ff terms into the CP2K codes too. Wish me luck, and thanks again.

**Comment by lvduyfhu** [comment]
Good luck :-)
